<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\EmailService\EmailService.csproj" />
    <ProjectReference Include="..\RedisService\RedisService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Command\" />
    <Folder Include="Features\Auth\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.2.2" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Infrastructure">
      <HintPath>..\Infrastructure\obj\Debug\net9.0\ref\Infrastructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
