using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.StoreProcedure
{
    public static class DBProcedures
    {
        public const string GetProducts = "GetProducts";
        public const string GetRiceTypes = "GetRiceTypes";
        public const string GetUnits = "GetUnits";
        public const string GetPositions = "GetPositions";
        public const string GetDepartments = "GetDepartments";
        public const string GetBanks = "GetBanks";
        public const string GetWareHouses = "GetWareHouses";
        public const string GetEmployees = "GetEmployees";
        public const string GetEmployeesByWareHouse = "GetEmployeesByWareHouse";
        public const string GetRicePackings = "GetRicePackings";
        public const string GetRices = "GetRices";
        public const string GetRicesByWareHouse = "GetRicesByWareHouse";
        public const string GetBusinessPartner = "GetBusinessPartner";
        public const string GetBusinessPartnerByWareHouse = "GetBusinessPartnerByWareHouse";
        public const string GetPartners = "GetPartners";
        public const string GetPartnerByWareHouse = "GetPartnerByWareHouse";
        public const string GetRiceReceipts = "GetRiceReceipts";
        public const string GetRiceReceiptDetail = "GetRiceReceiptsDetail";
        public const string GetAllWareHouseTransfer = "GetAllWareHouseTransfer";
        public const string GetTransferDetail = "GetTransferDetail";
        public const string GetTransferByWareHouses = "GetTransferByWareHouses";
        public const string GetInventoryReceiptByWareHouse = "GetInventoryReceiptByWareHouse";
        public const string GetInventoryReceiptDetail = "GetInventoryReceiptDetail";
        public const string GetPackingByWareHouses = "GetRicePackingByWareHouse";
        public const string GetRiceBoxes = "GetRiceBoxes";
        public const string GetRiceBoxesByWareHouse = "GetRiceBoxesByWareHouse";
        public const string GetRiceReceiptsByWareHouse = "GetRiceReceiptsByWareHouse";
        public const string GetSpendTypes = "GetSpendTypes";
        public const string GetRiceLots = "GetRiceLots";
        public const string GetBulkRices = "GetBulkRices";
        public const string GetRoles = "GetRoles";
        public const string FilterPackingData = "GetFilterPackingData";
        public const string GetMe = "GetMe";
        public const string GetBulkRicesByRiceLot = "GetBulkRicesByRiceLot";
        public const string GetOrdersByWareHouse = "GetOrdersByWareHouse";
        public const string GetPDFInfo = "GetPDFInfo";
        public const string GetBulkRiceOrdersByWareHouse = "GetBulkRiceOrdersByWareHouse";
        public const string GetBulkRiceOrderDetail = "GetBulkRiceOrderDetails";
        public const string GetBulkRiceOrderDetails = "GetBulkRiceOrderDetails";
        public const string GetRicePackingOrdersByWareHouse = "GetRicePackingOrdersByWareHouse";
        public const string GetRicePackingOrderDetails = "GetRicePackingOrderDetails";
        public const string GetPurchaseOrderByWareHouse = "GetPurchaseOrderByWareHouse";
        public const string GetPurchaseOrderDetail = "GetPurchaseOrderDetail";
        public const string GetPurchaseOrderPDFInfo = "GetPurchaseOrderPDFInfo";
        public const string GetRicePackingOrderPDFInfo = "GetRicePackingOrderPDFInfo";
        public const string GetBulkRiceOrderPDFInfo = "GetBulkRiceOrderPDFInfo";
        public const string GetSellRicesByWareHouse = "GetSellRicesByWareHouse";
        public const string GetSellBulkRiceByWareHouse = "GetSellBulkRiceByWareHouse";
        public const string GetRetailReceiptsByWareHouse = "GetRetailReceiptsByWareHouse";
        public const string GetTripSheetsByWareHouse = "GetTripSheetsByWareHouse";
        public const string GetReturnSellsByWareHouse = "GetReturnSellsByWareHouse";
        public const string GetBulkRiceTransferByWareHouse = "GetBulkRiceTransferByWareHouse";
        public const string GetRiceBulkRice = "GetRiceBulkRice";
        public const string GetPaymentVoucherByWareHouse = "GetPaymentVoucherByWareHouse";
        public const string GetPaymentVoucherPDFInFo = "GetPaymentVoucherPDFInfo";
        public const string GetSellRicePDFInfo = "GetSellRicePDFInfo";
        public const string GetSellBulkRicePDFInfo = "GetSellBulkRicePDFInfo";
        public const string GetReceiptVoucherByWareHouse = "GetReceiptVoucherByWareHouse";
        public const string GetReceiptVoucherPDFInfo = "GetReceiptVoucherPDFInfo";
        public const string WareHouseTransferInfo = "WareHouseTransferInfo";
        public const string BulkRiceWareHouseTransferInfo = "BulkRiceWareHouseTransferInfo";
        public const string GetDebtReport = "GetDebtReport";
        public const string GetSupplierDebit = "GetSupplierDebit";
        public const string GetPartnerDebit = "GetPartnerDebit";
        public const string GetCustomerDebit = "GetCustomerDebit";
        public const string GetWareHouseTransferReceiptVoucherByWareHouse = "GetWareHouseTransferReceiptVoucherByWareHouse";
        public const string GetWareHouseTransferReceiptVoucherPDFInfo = "GetWareHouseTransferReceiptVoucherPDFInfo";
        public const string GetWareHouseDebit = "GetWareHouseDebit";
        public const string GetRetailReceiptPDFInfo = "GetRetailReceiptPDFInfo";
        public const string GetDebitReport = "GetDebitReport";
        public const string GetPackingInventory = "GetPackingInventory";
        public const string GetRiceInventory = "GetRiceInventory";
        public const string GetBulkRiceInventory = "GetBulkRiceInventory";
        public const string GetLedger = "GetLedger";
        public const string GetReturnSellInfo = "GetReturnSellInfo";
        public const string GetTripSheetInfo = "GetTripSheetInfo";
        public const string GetFixedAssetsByWareHouse = "GetFixedAssetsByWareHouse";
        public const string GetDepreciationDetailsByFixedId = "GetDepreciationDetailsByFixedId";
        public const string GetInternalVoucherInfo = "GetInternalVoucherInfo";
        public const string GetInternalVouchersByWareHouse = "GetInternalVouchersByWareHouse";
        public const string GetRevenueReport = "GetRevenueReport";
        public const string GetRiceBuySellAnalyze = "GetRiceBuySellAnalyze";
        public const string GetBulkRiceBuySellAnalyze = "GetBulkRiceBuySellAnalyze";
        public const string GetOperatingCosts = "GetOperatingCosts";
        public const string TopSellRice = "TopSellRice";
        public const string GetOrdersToDeliver = "GetOrdersToDeliver";
        public const string GetBusinessPartnerDebitReportDetail = "GetBusinessPartnerDebitReportDetail";
        public const string ProfitReport = "GetProfitReport";
        public const string GetProfitReportDetail = "GetProfitReportDetail";
        public const string GetRevenueReportNotOrders = "GetRevenueReportNotOrders";
        public const string GetPaymentVoucherByReferenceId = "GetPaymentVoucherByReferenceId";
        public const string GetReceiptVoucherByReferenceId = "GetReceiptVoucherByReferenceId";
        public const string GetRiceReceiptInfo = "GetRiceReceiptInfo";
        public const string GetBulkRiceRiceLot = "GetBulkRiceRiceLot";
        public const string GetBulkRiceRiceLotDetail = "GetBulkRiceRiceLotDetail";
        public const string GetWareHouseDebitReportDetail = "GetWareHouseDebitReportDetail";
        public const string GetSupplierDebitReportDetail = "GetSupplierDebitReportDetail";
        public const string GetCustomerDebitDetail = "GetCustomerDebitDetail";
        public const string GetWareHouseTransferReceiptByTransferNo = "GetWareHouseTransferReceiptByTransferNo";
        public const string GetInternalVoucherObjects = "GetInternalVoucherObjects";
        public const string GetRiceLotByBulkRice = "GetRiceLotByBulkRice";
        public const string GetSellRiceNo = "GetSellRiceNo";
        public const string GetSellBulkRiceNo = "GetSellBulkRiceNo";
        public const string GetInventoryReceipts = "GetInventoryReceipts";

    }
}
